services:
  meneamebot:
    container_name: meneamebot
    hostname: meneamebot
    restart: always
    image: registry.meneame.bot:5000/meneamebot:v6
    cap_add:
      - SYS_ADMIN
    environment:
      - VIRTUAL_HOST=meneame.bot,www.meneame.bot
      - LETSENCRYPT_HOST=meneame.bot,www.meneame.bot
      - LETSENCRYPT_EMAIL=santiaguzz@gmail.com
    depends_on:
      mongo:
          condition: service_healthy
      milvus:
          condition: service_healthy
    networks:
      - meneamebot

  nginx:
    restart: always
    hostname: nginx
    container_name: nginx
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/nginx/certs:/etc/nginx/certs:ro
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/nginx/conf:/etc/nginx/conf.d:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - meneamebot

  letsencrypt:
    restart: always
    hostname: letsencrypt
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/nginx/certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - meneamebot

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - meneamebot

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - meneamebot

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.6.11
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - meneamebot

  mongo:
    restart: always
    container_name: mongo
    hostname: mongo
    image: mongo:noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mongostat", "-u", 'root', "-n", "1", "-p", "${MONGO_DB_PASSWORD}", "mongodb://localhost:27017/?authSource=admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - meneamebot

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - meneamebot

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/registry/certs:/certs:ro"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/registry/conf:/etc/docker/registry:ro"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/registry/storage:/var/lib/registry:rw"
    networks:
      - meneamebot

volumes:
  vhost:
  html:

networks:
  meneamebot:
    name: meneamebot
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
